### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by XhmikosR** [bezoerb/grunt-critical#31]
```
Running "critical:test-multiple-files-folder" (critical) task
Unhandled rejection Error: C:\Users\xmr\Desktop\grunt-critical\test\generated\multiple-files-folder\C:\Users\xmr\Desktop\grunt-critical\test\fixture contains invalid WIN32 path characters.
  at mkdirsSync (C:\Users\xmr\Desktop\grunt-critical\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:16:20)
  at Object.mkdirsSync (C:\Users\xmr\Desktop\grunt-critical\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:35:16)
  at Object.outputFileSync (C:\Users\xmr\Desktop\grunt-critical\node_modules\fs-extra\lib\output\index.js:28:9)
  at C:\Users\xmr\Desktop\grunt-critical\tasks\critical.js:117:24
  at tryCatcher (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\util.js:16:23)
  at Promise._settlePromiseFromHandler (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:502:31)
  at Promise._settlePromise (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:559:18)
  at Promise._settlePromise0 (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:604:10)
  at Promise._settlePromises (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:683:18)
  at Promise._fulfill (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:628:18)
  at Promise._resolveCallback (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:423:57)
  at Promise._settlePromiseFromHandler (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:514:17)
  at Promise._settlePromise (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:559:18)
  at Promise._settlePromise0 (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:604:10)
  at Promise._settlePromises (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:683:18)
  at Promise._fulfill (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:628:18)
  at PropertiesPromiseArray.PromiseArray._resolve (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise_array.js:125:19)
  at PropertiesPromiseArray._promiseFulfilled (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\props.js:78:14)
  at Promise._settlePromise (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:564:26)
  at Promise._settlePromise0 (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:604:10)
  at Promise._settlePromises (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:683:18)
  at Promise._fulfill (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:628:18)
  at Promise._resolveCallback (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:423:57)
  at Promise._settlePromiseFromHandler (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:514:17)
  at Promise._settlePromise (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:559:18)
  at Promise._settlePromise0 (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:604:10)
  at Promise._settlePromises (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:683:18)
  at Promise._fulfill (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:628:18)
  at MappingPromiseArray.PromiseArray._resolve (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise_array.js:125:19)
  at MappingPromiseArray._promiseFulfilled (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\map.js:97:18)
  at Promise._settlePromise (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:564:26)
  at Promise._settlePromise0 (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:604:10)
  at Promise._settlePromises (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\promise.js:683:18)
  at Async._drainQueue (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\async.js:138:16)
  at Async._drainQueues (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\async.js:148:10)
  at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xmr\Desktop\grunt-critical\node_modules\bluebird\js\release\async.js:17:14)
  at tryOnImmediate (timers.js:543:15)
  at processImmediate [as _immediateCallback] (timers.js:523:5)

```

And the process is stuck there.

We could set up AppVeyor like we do for Grunt/Grunt contrib in order to test Windows. I can make a PR if needed for this.

**Comment by bezoerb** [comment]
@XhmikosR i've added appveyor but i've currently no windows machine to test on.

**Comment by XhmikosR** [comment]
@bezoerb: you don't need one, those are the same errors I get :/

I will see tomorrow if I can update appveyor.yml, but it's irrelevant to the errors.

**Comment by XhmikosR** [comment]
OK, the problem is the pattern for some tasks.

Example

```js
src: 'test/fixture/multiple/index{1,2,3}.html',
```

I worked around it here https://github.com/bezoerb/grunt-critical/commit/ee5a15077eee91a47dd3a77ce3d4d3b02956d745

Not sure if we should work around it or fix it.

**Comment by bezoerb** [comment]
Thanks @XhmikosR. I think fixing is always the best option ;)

**Comment by XhmikosR** [comment]
All right, I'm closing this for now and we should revisit if needed in the future.
