### ISSUE TITLE
Unhandled rejection Error. Several errors: "socket hang up", "Wrong status code 502" and so on

### ISSUE THREAD

**Issue by shervud** [bezoerb/grunt-critical#46]
Hello, everyone. 
For example I've got url "https://www.cleanandclear.com.vn".

My config is:
  grunt.config('critical', {
    debug: {
      options: {
        base: './',
        timeout: 60000,
        penthouse: { "strict": false, "renderWaitTime": 5000, "blockJSRequests": false, "pageLoadSkipTimeout": 20000 },
        width: 1920,
        height: 1920,
        pathPrefix: ""
      },
      src: "https://www.cleanandclear.com.vn/",
      dest: "my-critical.css"
    }
  });

I use grunt-critical 0.3.0 and always get the following error:
Running "critical:debug" (critical) task
>> File "my-critical.css" failed. Error opening url 'https://www.cleanandclear.com.vn/': Connection closed

But I've found the same problem here https://github.com/addyosmani/critical/issues/240 and then I updated grunt-critical from 0.3.0 to 1.1.0 , which uses penthouse with Chrome headless, instead of PhantomJS.

But never mind is it grunt-critical 0.3.0 or 1.1.0, very rarely and randomly I am getting the following error:

**1st error:**
Unhandled rejection Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:120:20)
    at TLSSocket.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

This error appears randomly and I cannot even reproduce it, hence I cannot resolve it.
The worst thing is this error appear randomly, say on 9 of 10 times it's ok, and 1 of 10 it could fail. All options and parameters are similar, so I just don't have any idea...

**2nd error:**
Running "critical:debug" (critical) task
Unhandled rejection Error: Wrong status code 502 for https://example.com/some-css.css
at Request.request [as _callback] (/node_modules/critical/lib/file-helper.js:146:31)
at Request.self.callback (/node_modules/request/request.js:188:22)
at emitTwo (events.js:135:13)
at Request.emit (events.js:224:7)
at Request.<anonymous> (/node_modules/request/request.js:1171:10)
at emitOne (events.js:125:13)
at Request.emit (events.js:221:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:1091:12)
at Object.onceWrapper (events.js:322:30)
at emitNone (events.js:120:20)
at IncomingMessage.emit (events.js:218:7)
at endReadableNT (_stream_readable.js:1054:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)

So, likely my main question: is there any way to apply and implement "try {} catch () {}" and wrap grunt.task.run('critical') into try?
Because any **Unhandled rejection Error** just brakes full deploy of my website. 1st error is even worst, It could appear randomly, for example after 3 hours of deploy it could appear and brake down the deploy.
If any one knows how to handle Unhandled rejection Error it would be great if you say how it could be resolved.
Thank you.

**Comment by bezoerb** [comment]
@shervud: sorry for the late response. This error seems like a problem with the server and not with critical itself. Can you verify that this error doesn't occur without critical?
