### ISSUE TITLE
(node:9421) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Romkond** [bezoerb/grunt-critical#49]
There were issues while installing the plugin (however I did it like `sudo npm install grunt-critical --unsafe-perm=true`)
Now there's an error while launching it:
```
(node:9421) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/sfocus/web/seo-focus.cl/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/sfocus/web/seo-focus.cl/node_modules/puppeteer/lib/Launcher.js:226:14)
    at Interface.helper.addEventListener (/home/sfocus/web/seo-focus.cl/node_modules/puppeteer/lib/Launcher.js:215:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:9421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Node v8.11.1
Npm 6.0.0

**Comment by Minirock** [comment]
I had the same issue. It's because you miss some dependencies.

This will solve your problem:

`sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
`

**Comment by bezoerb** [comment]
Thanks @Minirock
