### ISSUE TITLE
Process multiple files

### ISSUE THREAD

**Issue by ozasadnyy** [bezoerb/grunt-critical#6]
Hello!
How can I process multiple files? Because this task:
```
critical: {
            dist: {
                options: {
                    base: './',
                    css: [
                        '.tmp/css/blog.css'
                    ],
                    minify: true,
                    width: 320,
                    height: 480
                },
                src: '<%= yeoman.dist %>/**/*.html',
                dest: '<%= yeoman.dist %>/**/*.html'
            }
        }
```

Gives me following error:
```
Running "critical:dist" (critical) task
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:773:26)
    at module.exports (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\penthouse\lib\index.js:50:13)
    at ret (eval at makeNodePromisifiedEval (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\promisify.js:177:12), <anonymous>:12:26)
    at F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\src\critical.js:168:16
    at tryCatch1 (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\util.js:21:21)
    at Promise._settlePromiseFromHandler (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\promise.js:591:13)
    at Promise._settlePromiseAt (F:\development\web\sitey.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\promise.js:755:18)
    at Async._drainQueue (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\async.js:83:12)
    at Async._drainQueues (F:\development\web\site.com\node_modules\grunt-critical\node_modules\critical\node_modules\bluebird\js\main\async.js:88:10)
Fatal error: Unable to create directory "F:\development\web\site.com\dist\**" (Error code: ENOENT).
```

**Comment by bezoerb** [comment]
Hey @ozasadnyy,
the memory leak issue should be fixed now. 
To process multiple files you should use the following syntax though:
```javascript
critical: {
    dist: {
        options: {
            base: './',
            css: [
                '.tmp/css/blog.css'
            ],
            minify: true,
            width: 320,
            height: 480
        },
        files: [
            {expand: true, cwd: '<%= yeoman.dist %>', src: ['**/*.html'], dest: '.'}
        ]
    }
}
```

**Comment by ozasadnyy** [comment]
It works, thanks!

**Comment by ozasadnyy** [comment]
Hello, @bezoerb again!
It processes multiple files, but incorrectly..
It replaces all `.html` files with one of them. In my case with file from last subfolder.
[Here](https://github.com/zasadnyy-inc/v-zasadnyy-com) is my repository of project.

**Comment by bezoerb** [comment]
Hey @ozasadnyy,
i'll check out your repository and try to fix this. 
Thanks for reporting

**Comment by bezoerb** [comment]
The multiple file issue is fixed now. I've modified the testcase to address this issue and released a new version but i would wait for https://github.com/bezoerb/grunt-critical/issues/7 to be fixed before updating the module

**Comment by ozasadnyy** [comment]
ok, thanks a lot!
